#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: sandbox/canary-gen.sh --target-dir DIR [--run-id RUN_ID] [--no-kubeconfig]

Generates per-run fake secrets into DIR and writes DIR/canary.json.
DIR is the only output location and is intended to be mounted into the sandbox.

Environment:
  EXFIL_CANARY_TARGET_DIR  Alternative to --target-dir.
  EXFIL_RUN_ID             Alternative to --run-id.
USAGE
}

fail() {
  echo "canary-gen.sh: $*" >&2
  exit 1
}

target_dir="${EXFIL_CANARY_TARGET_DIR:-}"
run_id="${EXFIL_RUN_ID:-}"
include_kubeconfig=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-dir)
      [[ $# -ge 2 ]] || fail "--target-dir requires a value"
      target_dir="$2"
      shift 2
      ;;
    --run-id)
      [[ $# -ge 2 ]] || fail "--run-id requires a value"
      run_id="$2"
      shift 2
      ;;
    --no-kubeconfig)
      include_kubeconfig=0
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[[ -n "$target_dir" ]] || {
  usage
  exit 2
}

command -v python3 >/dev/null 2>&1 || fail "python3 is required"

python3 - "$target_dir" "$run_id" "$include_kubeconfig" <<'PY'
import base64
import json
import os
import stat
import sys
from datetime import datetime, timezone
from pathlib import Path

# ref: /home/mrg/Desktop/exfil-step-a-refs/canarytokens/canarytokens/constants.py:17
CANARYTOKEN_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"
# ref: /home/mrg/Desktop/exfil-step-a-refs/canarytokens/canarytokens/constants.py:18
CANARYTOKEN_LENGTH = 25
AWS_KEY_ID_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
AWS_SECRET_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/+"


def random_chars(alphabet: str, length: int) -> str:
    # Direct CSPRNG source; no shell $RANDOM/date-derived entropy.
    with open("/dev/urandom", "rb", buffering=0) as rng:
        out = []
        limit = (256 // len(alphabet)) * len(alphabet)
        while len(out) < length:
            for byte in rng.read(64):
                if byte < limit:
                    out.append(alphabet[byte % len(alphabet)])
                    if len(out) == length:
                        break
    return "".join(out)


def canary_token() -> str:
    return random_chars(CANARYTOKEN_ALPHABET, CANARYTOKEN_LENGTH)


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def write_secret(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(text)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def add_secret(catalog: dict, secret_type: str, path: Path, token: str, env_name: str | None = None) -> None:
    item = {
        "secret_id": f"{secret_type}-{token[:8]}",
        "type": secret_type,
        "path": str(path),
        "match_token": token,
    }
    if env_name is not None:
        item["env_name"] = env_name
    catalog["secrets"].append(item)


target = Path(sys.argv[1]).expanduser().resolve()
run_id = sys.argv[2] or f"run-{canary_token()}"
include_kubeconfig = sys.argv[3] == "1"
target.mkdir(parents=True, exist_ok=True)

catalog = {
    "run_id": run_id,
    "generated_at": utc_now(),
    "secrets": [],
}

ssh_token = canary_token()
ssh_material = base64.b64encode(
    f"fake-rsa-private-key:{run_id}:{ssh_token}:{random_chars(CANARYTOKEN_ALPHABET, 40)}".encode()
).decode()
ssh_body = "\n".join(ssh_material[index : index + 64] for index in range(0, len(ssh_material), 64))
ssh_path = target / "canary_rsa"
write_secret(
    ssh_path,
    "\n".join(
        [
            "# fake private key generated by exfil-analyzer",
            f"# canary-token: {ssh_token}",
            "-----BEGIN RSA PRIVATE KEY-----",
            ssh_body,
            "-----END RSA PRIVATE KEY-----",
            "",
        ]
    ),
)
add_secret(catalog, "canary_rsa", ssh_path, ssh_token)

# ref: /home/mrg/Desktop/exfil-step-a-refs/canarytokens/canarytokens/models/aws_keys.py:20
aws_token = canary_token()
aws_access_key_id = "AKIA" + random_chars(AWS_KEY_ID_ALPHABET, 16)
aws_secret_key = aws_token + random_chars(AWS_SECRET_ALPHABET, 40 - len(aws_token))
aws_path = target / ".aws" / "credentials"
write_secret(
    aws_path,
    "\n".join(
        [
            "[default]",
            f"aws_access_key_id = {aws_access_key_id}",
            f"aws_secret_access_key = {aws_secret_key}",
            "region = us-east-1",
            "",
        ]
    ),
)
add_secret(catalog, "aws_access_key", aws_path, aws_token)

env_token = canary_token()
env_path = target / ".env"
write_secret(
    env_path,
    "\n".join(
        [
            "APP_ENV=production",
            f"EXFIL_CANARY_TOKEN={env_token}",
            "",
        ]
    ),
)
add_secret(catalog, "env_token", env_path, env_token, "EXFIL_CANARY_TOKEN")

if include_kubeconfig:
    # ref: /home/mrg/Desktop/exfil-step-a-refs/canarytokens/canarytokens/kubeconfig.py:99
    kube_token = canary_token()
    kube_cert = base64.b64encode(f"fake-ca:{kube_token}".encode()).decode()
    kube_client_cert = base64.b64encode(f"fake-client-cert:{kube_token}".encode()).decode()
    kube_client_key = base64.b64encode(f"fake-client-key:{kube_token}".encode()).decode()
    kube_user = f"svc-{kube_token[:10]}"
    cluster_name = "k8s-prod-cluster"
    kube_path = target / "kubeconfig"
    write_secret(
        kube_path,
        "\n".join(
            [
                "apiVersion: v1",
                "kind: Config",
                "clusters:",
                f"- name: {cluster_name}",
                "  cluster:",
                f"    server: canary-{kube_token}.k8s.invalid:6443",
                f"    certificate-authority-data: {kube_cert}",
                "users:",
                f"- name: {kube_user}",
                "  user:",
                f"    client-certificate-data: {kube_client_cert}",
                f"    client-key-data: {kube_client_key}",
                "contexts:",
                f"- name: {kube_user}-{cluster_name}",
                "  context:",
                f"    cluster: {cluster_name}",
                f"    user: {kube_user}",
                f"current-context: {kube_user}-{cluster_name}",
                "",
            ]
        ),
    )
    add_secret(catalog, "kubeconfig", kube_path, kube_token)

catalog_path = target / "canary.json"
write_secret(catalog_path, json.dumps(catalog, ensure_ascii=False, indent=2) + "\n")
print(catalog_path)
PY
